[phases.setup]
phpExtensions = ["gd", "zip", "curl", "json", "mysqli", "intl", "openssl", "ctype", "dom", "fileinfo", "filter", "hash", "mbstring", "pcre", "pdo", "session", "tokenizer", "xml", "pdo_mysql", "redis"]
